title: Spring data Gigaspaces
lsi: false
safe: true
incremental: false
highlighter: rouge
# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-sitemap
